### ISSUE TITLE
Garbled screen on O2 with Voice attached 

### ISSUE THREAD

**Issue by MrSeven-LV** [aotta/PicoPAC#1]
I get nothing but random Odyssey characters when I attempt to use this on an Odyssey 2 with The Voice module attached. When I remove The Voice, the menu shows up and I can scroll through all the games. I was only able to load and play Smithereens. Any attempt to load any other game results in the menu locking up. All ROMs were acquired from the site recommended and they all reside in the root directory of the Pi.

**Comment by aotta** [comment]
Some incompatibility with Voice is known even for the original microsdcart, i haven't it so i can't troubleshooting or fix it.
About issue with all games but one, i didn't tested the cart with a ntsc O2 but it should work same way of Videopac. please check that filenames of rom in flash match with list in filelist.h (and just found a mistake in line 48! 😂 ), and please report what if you press reset, and if pico blinks with an error code, and in case how many flashes you got .

**Comment by MrSeven-LV** [comment]
No worries on my game loading problem, it was my fault. After I saw that it wasn't working with The Voice, I re-flashed it, got side tracked for a while and completely forgot that I didn't copy all the ROMs back. It works great just like all your other Pico carts. I feel silly now. 

Understood on The Voice incompatibility. My O2 looks naked without it. 😂

I don't know if there is a difference in the way the PCB mounts in a Videopac cartridge, but in order to fit it inside an O2 cartridge shell, I had to increase the size of the notches about 4-5mm. No big deal, it fits perfect. 

Thanks for the quick response, all my issues have been taken care of. Great work BTW. Now where are those 2600 and 5200 Pico carts? 😂

**Comment by aotta** [comment]
Happy you solved, i hope one day to get a Voice (i read about a sort of adapter for Videopac on a forum) and solve the incompatibiliry with PicoPAC.
I don't have a 5200 so no plan for a flashcart for it, but Pico2600 is one of the next on my todo list... stay tuned! ;)

**Comment by PhilDPino** [comment]
Came here to see if a solution was found for the Voice incompatibility? Is it a shell fitting/notch issue or a firmware update needed?

**Comment by PhilDPino** [comment]
Also would be interested in a 5200 Pico

**Comment by aotta** [comment]
Not yet got a The Voice nor an Atari 5200 to work on them.
If you want to donate them to me i remain available ;)
