### ISSUE TITLE
Does not work on G7000

### ISSUE THREAD

**Issue by Ahnl66** [aotta/PicoPAC#2]
Hi, I built the card, and I think hardware is OK. But when I run it in the G7000 it starts with garbled screen. When I press reset, I do see the pi pac screen, and next it is garbled again.  I did try a couple of things:
- I renamed a game to select game.bin, and indeed it looks like the game starts when I startup the console, but the game is corrupt and doesn't work.
- I recompiled the VSC-PicoPac and flashed Pico again, did not help. In picopac_cart.c I changed the set_sys_clock_khz to 179000 and also to 360000 - did not help
- i deleted all files, except for selectgame.bin. Then there is only a garbled screen, the reset does not do anything.

My conclusions so far
- hardware seems OK. Otherwise I think it would not work at all
- selectgame.bin is OK. Otherwise when I renamed a game to selectgame.bin, it would work
- So I think problem is in VSC-PicoPac, and likely something with reading the filesystem. It seems when loading a file from disk the wrong sectors/data is read
- Strange thing is that when I start up the console, immediately screen is garbled. And only when I press reset the pi pac screen appears, so it seems to skip something at boot.

Any clue what I could try next?

PS: I do not need to put ALL te files on the pico, I put on the vp ones and the selectgame.bin. Or do I need to put everything on?

Thanks for a great project!

Arthur

https://github.com/user-attachments/assets/9c502dd6-ab86-492e-9e40-31276e60a1a2

**Comment by moparisthebest** [comment]
My North American Odyssey 2 behaves the exact same way with this cart

**Comment by aotta** [comment]
Uploaded new uf2 and selectgame.bin that should work with G7000

**Comment by Ahnl66** [comment]
Thanks so much - it works! Very interested to understand the fixes you made, would be great if you could update the code in git so I can learn.

**Comment by aotta** [comment]
Yes i just fixed the VP_31 and VP_40 XROM games that didn't work. I'll update all in few minutes
