### ISSUE TITLE
Jet25-Radiola no menu on screen on boot

### ISSUE THREAD

**Issue by repetto74** [aotta/PicoPAC#3]
Hello Aotta,

I have built this nice PicoPAC for a JET25 made by Radiola (should be the french version of the C25 tested working).

I programmed the Pico with latest firmware then added the Select Game.bin and a set of bin roms taken from the link you provided.
Unfortunately I just do not reach the menu screen but I'll get the messy screen when a cart is not inserted.
This JET25 is of course working with original carts. 
The green led of the Pico flashes 2 times in a loop.
What could be wrong here?
Thanks in advance for any valuable suggestion :-)
![IMG_7230](https://github.com/user-attachments/assets/abe48016-4aa4-48af-8f58-cce054f94652)
![IMG_7231](https://github.com/user-attachments/assets/ad14065e-99b6-4e39-b4e3-1ff3bbe86e19)

**Comment by repetto74** [comment]
Just a quick comment. The OS is indeed in french so do not know how much this can interfere with the Pico firmware. Maybe I need to rename the Select Game.bin? Just a blind guess.

**Comment by aotta** [comment]
Read twice the notes on readme, you must upload both .bin and .$$$ files

Il ven 20 set 2024, 12:48 repetto74 ***@***.***> ha scritto:

**Comment by aotta** [comment]
No issue

**Comment by repetto74** [comment]
Thanks indeed I missed the $$$ file. All is working now :-).
