### ISSUE TITLE
Writing more then +/_ 178 roms to root gives write error 

### ISSUE THREAD

**Issue by snikhaas** [aotta/PicoPAC#4]
Hi,

I was trying to add extra roms to the root of the picopac  , but notices that it gives me write errors when there are more then 178-ish roms in the root..
Can copy extra files in a sub dir, but those are not available in pico pac menu...

Is this a fat limitation or something that can be fixed in a future fw update ?

Ps,  I modified the 3D case and added holes for  reset and usb-c...
I made it available on thingiverse... if not allowed please let now, dont want to step on anyones toes ...and feel free to ad the files to this project.
All credits to original designer..

https://www.thingiverse.com/thing:6864410

**Comment by aotta** [comment]
Most of the filelist structure is "hardcoded" in selectgame.bin, i modified the original one by Wilco a bit, but supporting more files or subfolder management would imply a total rewriting of the selectgame that's out of my scope

**Comment by snikhaas** [comment]
Thanks for getting back to me. 👍🏻

Now I know there's nothing wrong with my pi zero clone..

Have a nice day.

Best regards
